RuleTool/Models/ErrorViewModel.cs
using System;

namespace RuleTool.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RuleTool/Models/Rule.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace RuleTool.Models
{
    public class Rule
    {
        public int id { get; set; }
        [Required]
        public string Name { get; set; }
        [Display(Name = "Value")]
        [Required]
        public string FieldLeft { get; set; }
        [Required]
        public string Operator { get; set; }
        [Display(Name = "Value")]
        [Required]
        public string FieldRight { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Creator { get; set; }
        public string Region { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date of Creation")]
        public DateTime CreationDate { get; set; }

    }
}

RuleTool/Controllers/HelloRuleToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RuleTool.Controllers
{
    public class HelloRuleToolController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

RuleTool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RuleTool.Models;

namespace RuleTool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Overview()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RuleTool/Controllers/RulesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RuleTool.Data;
using RuleTool.Models;

namespace RuleTool.Controllers
{
    public class RulesController : Controller
    {
        private readonly RuleToolContext _context;

        public RulesController(RuleToolContext context)
        {
            _context = context;
        }

        // GET: Rules
        public async Task<IActionResult> Index(string searchString)
        {
            var rules = from m in _context.Rule
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                rules = rules.Where(s => s.Name.Contains(searchString));
            }

            return View(await rules.ToListAsync());
        }

        // GET: Rules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rule = await _context.Rule
                .FirstOrDefaultAsync(m => m.id == id);
            if (rule == null)
            {
                return NotFound();
            }

            return View(rule);
        }

        // GET: Rules/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Rules/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Name,FieldLeft,Operator,FieldRight,Description,Creator,Region,CreationDate")] Rule rule)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rule);
        }

        // GET: Rules/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rule = await _context.Rule.FindAsync(id);
            if (rule == null)
            {
                return NotFound();
            }
            return View(rule);
        }

        // POST: Rules/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Name,FieldLeft,Operator,FieldRight,Description,Creator,Region,CreationDate")] Rule rule)
        {
            if (id != rule.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rule);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RuleExists(rule.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rule);
        }

        // GET: Rules/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rule = await _context.Rule
                .FirstOrDefaultAsync(m => m.id == id);
            if (rule == null)
            {
                return NotFound();
            }

            return View(rule);
        }

        // POST: Rules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rule = await _context.Rule.FindAsync(id);
            _context.Rule.Remove(rule);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RuleExists(int id)
        {
            return _context.Rule.Any(e => e.id == id);
        }
    }
}

RuleTool/Views/Home/Create.cshtml
@{
    ViewData["Title"] = "Create";
}
<h2>@ViewData["Title"]</h2>

<p>Use this page to create a new rule.</p>

RuleTool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Homepage";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the RuleTool!</h1>
    <p>Maintain your Business Rules.</p>
</div>

RuleTool/Views/Home/Overview.cshtml
@{
    ViewData["Title"] = "Overview";
}
<h2>@ViewData["Title"]</h2>

<p>Use this page to create a new rule.</p>

RuleTool/Views/Rules/Create.cshtml
@model RuleTool.Models.Rule

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Rule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FieldLeft" class="control-label"></label>
                <input asp-for="FieldLeft" class="form-control" />
                <span asp-validation-for="FieldLeft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Operator" class="control-label"></label>
                <input asp-for="Operator" class="form-control" />
                <span asp-validation-for="Operator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FieldRight" class="control-label"></label>
                <input asp-for="FieldRight" class="form-control" />
                <span asp-validation-for="FieldRight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator" class="control-label"></label>
                <input asp-for="Creator" class="form-control" />
                <span asp-validation-for="Creator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RuleTool/Views/Rules/Delete.cshtml
@model RuleTool.Models.Rule

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rule</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FieldLeft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FieldLeft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Operator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FieldRight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FieldRight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Creator)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RuleTool/Views/Rules/Details.cshtml
@model RuleTool.Models.Rule

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Detail for @Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FieldLeft)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FieldLeft)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Operator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Operator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FieldRight)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FieldRight)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Creator)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Creator)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

RuleTool/Views/Rules/Edit.cshtml
@model RuleTool.Models.Rule

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>For Rule: @Model.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FieldLeft" class="control-label"></label>
                <input asp-for="FieldLeft" class="form-control" />
                <span asp-validation-for="FieldLeft" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Operator" class="control-label"></label>
                <input asp-for="Operator" class="form-control" />
                <span asp-validation-for="Operator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FieldRight" class="control-label"></label>
                <input asp-for="FieldRight" class="form-control" />
                <span asp-validation-for="FieldRight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Creator" class="control-label"></label>
                <input asp-for="Creator" class="form-control" />
                <span asp-validation-for="Creator" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

RuleTool/Views/Rules/Index.cshtml
@model IEnumerable<RuleTool.Models.Rule>

@{
    ViewData["Title"] = "Overview";
}

<h1>Rules Overview</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Rules" asp-action="Index">
      <p>
          Search for <input type="text" name="SearchString">
          <input type="submit" value="Filter" />
      </p>
      </form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

RuleTool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RuleTool</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RuleTool</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rules" asp-action="Index">Overview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rules" asp-action="Create">Create</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - RuleTool
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>